// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qentcwkwmmndtaetriht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlbnRjd2t3bW1uZHRhZXRyaWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjExOTYsImV4cCI6MjA2NjUzNzE5Nn0.uOcFjLc6WGm-VOhxnCbGWqjVjnab1gWxAFBz-v3gScc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);